#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <sys/ioctl.h>

typedef struct 
{
	char REC[256]; //Data generated by external system(256 byte/packet)
	int DATA; //Current counter value
	int MATCH; //Generate interrupt value (compared to DATA)
	int START; //Start value for counter
	int END; // End value for counter
	int ENABLE; // Write 1 to enable counter
	int DISABLE; //Write 1 to disable counter
	int STATUS; // Interrupt status register (how many times interrupt occured)
	int CLEAR; // Write 1 to enable interrupt
}FPGA;
static int fd;

void set_start(int value);
void set_end(int value);
void enable();
void disable();
int read_value();
void set_match(int value);
int read_status();

int main()

{
	int i;
	char buffer[256];
	
	fd = open("/dev/myfpga", O_RDWR | O_SYNC , 0);
	
/*
	//------------- mmap test ---------------------------
	
	
	FPGA* myfpga =  mmap(0 ,0x1000 ,PROT_READ|PROT_WRITE, MAP_SHARED ,fd , 0);
	close(fd);
	
	for( i = 0 ; i < 256 ; i++)
	{
		printf("%c", myfpga->REC[i]);
	}
	printf("\n");
	myfpga->START = 10;
	myfpga->END = 100;
	myfpga->MATCH = 15;
	myfpga->ENABLE = 1;
	printf("counter value = %d\n",myfpga->DATA);
	sleep(10);
	myfpga->DISABLE = 1;
	
	
	//-----------end mmap test ---------------------------------
	
*/
	//---------- read and ioctl test ---------------------------  
	
	read(fd, buffer , 256);
	for (i = 0; i < 256 ; i++)
	{
		printf("%c", buffer[i]);
	}
	printf("\n");
	set_start(10);
	set_end(20);
	set_match(15);
	enable();
	printf("counter value = %d\n", read_value());
	sleep(10);
	printf("No. of interrupts that has occured = %d\n", read_status());
	disable();
	
	// ----------end read and ioctl test ------------------------

   return 0;
}


void set_start(int value)
{
	ioctl(fd,10,value);
	
}
void set_end(int value)
{
	ioctl(fd,20,value);
}

void enable()
{
	ioctl(fd,30,0);
	
}
void disable()
{
	ioctl(fd,40,0);
}
int read_value()
{
	return ioctl(fd,50,0);
}
void set_match(int value)
{
	ioctl(fd,60,value);
}
int read_status()
{
	return ioctl(fd,70,0);
	
}
